
# Configuration for the MLOps XGBoost Project - TEST

# --- Data Parameters ---
data:
  target_column: "churn"
  n_samples: 100
  n_features: 5
  noise_level: 0.1
  test_size: 0.5
  random_state: 42

# --- Model Parameters ---
model:
  name: "test_xgboost_regression_model"
  params:
    tree_method: "hist"
    n_estimators: 10
    learning_rate: 0.1
    max_depth: 3
    subsample: 0.8
    colsample_bytree: 0.8
    eval_metric: "rmse"

# --- Hyperparameter Tuning Parameters ---
tuning:
  n_trials: 2
  objective_metric: "rmse"
  direction: "minimize"
  sampler: "random"
  pruner: "nop"

# --- MLflow Parameters ---
mlflow:
  experiment_name: "Test_XGBoost_Regression"

# --- Visualization Parameters ---
visualization:
  output_dir: "test_visualizations"
