
name: MLOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set up Kaggle API credentials
      uses: robert-david-graham/kaggle-api-credential-action@v1
      with:
        kaggle-username: ${{ secrets.KAGGLE_USERNAME }}
        kaggle-key: ${{ secrets.KAGGLE_KEY }}
    - name: Run Data Ingestion
      run: |
        python -m src.ingest_data
    - name: Run Feature Engineering
      run: |
        python -m src.build_features
    - name: Test with pytest
      run: |
        pytest

  run_pipeline:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and run Docker container
      run: |
        docker build -t olist-churn-predictor .
        docker run olist-churn-predictor
